import {
  Bell,
  BookOpen,
  Calendar,
  ClipboardList,
  DollarSign,
  FileText,
  LayoutDashboard,
  ShieldCheck,
  User,
  Users,
  BarChart3,
  BadgeCheck,
} from "lucide-react"

export const teachersSidebarItems = [
  { title: "Dashboard", href: "/dashboard/teachers", icon: LayoutDashboard },
  { title: "My Profile", href: "/dashboard/teachers/profile", icon: User },
  { title: "My Students", href: "/dashboard/teachers/students", icon: Users },
  { title: "My Classes", href: "/dashboard/teachers/classes", icon: Calendar },
  { title: "My Schedule", href: "/dashboard/teachers/schedule", icon: Calendar },
  { title: "My Trials", href: "/dashboard/teachers/trials", icon: ClipboardList },
  { title: "My Earnings", href: "/dashboard/teachers/earnings", icon: DollarSign },
  { title: "Complaints", href: "/dashboard/teachers/complaints", icon: ShieldCheck },
  { title: "Teaching Record", href: "/dashboard/teachers/teaching-record", icon: FileText },
  { title: "Performance", href: "/dashboard/teachers/performance", icon: BarChart3 },
  { title: "Leaves", href: "/dashboard/teachers/leaves", icon: BookOpen },
  { title: "Notifications", href: "/dashboard/teachers/notifications", icon: Bell },
  { title: "Management", href: "/dashboard/teachers/management", icon: BadgeCheck, roles: ["manager", "admin", "ceo"] },
]
